-- MySQL Script generated by MySQL Workbench
-- 05/22/17 18:38:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tecweb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tecweb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tecweb` DEFAULT CHARACTER SET utf8 ;
USE `tecweb` ;

-- -----------------------------------------------------
-- Table `tecweb`.`Utente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecweb`.`Utente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cognome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `genere` VARCHAR(255) NOT NULL,
  `data_di_nascita` DATE NOT NULL,
  `provincia` VARCHAR(255) NOT NULL,
  `città` VARCHAR(255) NOT NULL,
  `telefono` INT NULL,
  `data_registrazione` DATETIME NOT NULL,
  `ultimo_accesso` DATETIME NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `tecweb`.`Azienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecweb`.`Azienda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `descrizione` TEXT NOT NULL,
  `ragione_sociale` VARCHAR(255) NOT NULL,
  `localizzazione` VARCHAR(255) NOT NULL,
  `tipologia` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tecweb`.`Categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecweb`.`Categorie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `descrizione` TINYTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tecweb`.`Coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecweb`.`Coupon` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `descrizione` TEXT NOT NULL,
  `categoria` VARCHAR(255) NOT NULL,
  `inizio_validità` DATETIME NOT NULL,
  `scadenza` DATETIME NOT NULL,
  `luogo_di_fruizione` VARCHAR(255) NOT NULL,
  `N°emissioni` INT NOT NULL,
  `idAzienda` INT NOT NULL,
  `idCategorie` INT NOT NULL,
  PRIMARY KEY (`id`, `idAzienda`, `idCategorie`),
  INDEX `fk_Coupon_Azienda1_idx` (`idAzienda` ASC),
  INDEX `fk_Coupon_Categorie1_idx` (`idCategorie` ASC),
  CONSTRAINT `fk_Coupon_Azienda1`
    FOREIGN KEY (`idAzienda`)
    REFERENCES `tecweb`.`Azienda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Coupon_Categorie1`
    FOREIGN KEY (`idCategorie`)
    REFERENCES `tecweb`.`Categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `tecweb`.`Cronologia_Coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecweb`.`Cronologia_Coupon` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUtente` INT NOT NULL,
  `idCoupon` INT NOT NULL,
  `data_emissione` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `idUtente`, `idCoupon`),
  INDEX `fk_Cronologia_Coupon_Utente_idx` (`idUtente` ASC),
  INDEX `fk_Cronologia_Coupon_Coupon1_idx` (`idCoupon` ASC),
  CONSTRAINT `fk_Cronologia_Coupon_Utente`
    FOREIGN KEY (`idUtente`)
    REFERENCES `tecweb`.`Utente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cronologia_Coupon_Coupon1`
    FOREIGN KEY (`idCoupon`)
    REFERENCES `tecweb`.`Coupon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tecweb`.`Admin-Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecweb`.`Admin-Staff` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cognome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `genere` VARCHAR(255) NOT NULL,
  `ultimo_accesso` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tecweb`.`Credenziali`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecweb`.`Credenziali` (
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `livello_di_accesso` INT NOT NULL,
  `idAdmin-Staff` INT NOT NULL,
  `idUtente` INT NOT NULL,
  PRIMARY KEY (`idAdmin-Staff`, `idUtente`, `username`),
  INDEX `fk_table1_Utente1_idx` (`idUtente` ASC),
  CONSTRAINT `fk_table1_Admin/Staff1`
    FOREIGN KEY (`idAdmin-Staff`)
    REFERENCES `tecweb`.`Admin-Staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_Utente1`
    FOREIGN KEY (`idUtente`)
    REFERENCES `tecweb`.`Utente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
