<div class="container">
    <br>
    <h3><b>Cancellazione promozione avvenuta con successo!</b></h3>
    <br>
    <a href=" <?= $this->url(array(
                                    'controller' => 'staff',
                                    'action'     => 'coupon',
                                    ), 
                                    'default',true); 
                                    ?>">Modifica/cancella altre promozioni</a>
    <a href=" <?= $this->url(array(
                                    'controller' => 'staff',
                                    'action'     => 'index',
                                    ), 
                                    'default',true); 
                                    ?>">Torna alla pagina degli strumenti</a>
</div>


