<div class="container">
    <br><br>
    <a class="btn btn-primary" href="<?= $this->url(array(
                                    'controller' => 'staff',
                                    'action'     => 'strumenti',
                                    ), 
                                    'default',true); 
                                    ?>">< Strumenti Staff</a><br><br>
    <form action="<?= $this->url(array(
                                    'controller' => 'staff',
                                    'action'     => 'formcouponmod',
                                    ), 
                                    'default',true); 
                        ?>" method="get">
        <table class="table table-condensed">
            <tr><th style="text-align:center;">Seleziona</th><th>ID</th><th>Nome</th><th>Descrizione</th><th>Inizio validit&agrav&agrave;</th>
                <th>Scadenza</th><th>Luogo di fruizione</th><th>Categoria</th><th>Azienda</th>
                <th>Tot. emissioni</th><th>Immagine</th>
            <?php
                foreach ($this->coupon as $coupon){
                    if($coupon->immagine==null){
                        $immagine = 'NON DISPONIBILE';
                    }
                    else{
                        $immagine = $coupon->immagine;
                    }
                echo '<tr><td style="text-align:center;"><input type="radio" name="chosen" value="' . $coupon->id . '"</td>'
                        . '<td>' . $coupon->id . '</td>'
                        . '<td>' . $coupon->nome . '</td>'
                        . '<td>' . $coupon->descrizione . '</td>'
                        . '<td>' . $coupon->inizio_validita . '</td>'
                        . '<td>' . $coupon->scadenza . '</td>'
                        . '<td>' . $coupon->luogo_di_fruizione . '</td>'
                        . '<td>' . $coupon->idCategoria . '</td>'
                        . '<td>' . $coupon->idAzienda . '</td>'
                        . '<td>' . $coupon->emissioni . '</td>'
                        . '<td>' . $immagine . '</td>';
            }?>
        </table>
        <br>
        <input class="btn btn-primary" type="submit" name="button"  value="Modifica/Cancella">
    </form>
</div>
