<div class="container">
    <br><br>
    <a class="btn btn-primary" href="<?= $this->url(array(
                                    'controller' => 'staff',
                                    'action'     => 'strumenti',
                                    ), 
                                    'default',true); 
                                    ?>">< Strumenti Staff</a><br><br>
    <form action="<?= $this->url(array(
                                    'controller' => 'staff',
                                    'action'     => 'formcouponmod',
                                    ), 
                                    'default',true); 
                        ?>" method="get">
        <table class="table table-condensed">
            <tr><th style="text-align:center;">Seleziona</th><th>ID</th><th>Nome</th><th>Descrizione</th><th>Inizio validit&agrav&agrave;</th>
                <th>Scadenza</th><th>Luogo di fruizione</th><th>Categoria</th><th>Azienda</th>
                <th>Tot. emissioni</th><th>Immagine</th>
            <?php
                foreach ($this->coupon as $promozione){
                    if($promozione['immagine']==null){
                        $immagine = 'NON DISPONIBILE';
                    }
                    else{
                        $immagine = $promozione['immagine'];
                    }
                echo '<tr><td style="text-align:center;"><input type="radio" name="chosen" value="' . $promozione['id'] . '"</td>'
                        . '<td>' . $promozione['id'] . '</td>'
                        . '<td>' . $promozione['nome'] . '</td>'
                        . '<td>' . $promozione['descrizione'] . '</td>'
                        . '<td>' . $promozione['inizio_validita'] . '</td>'
                        . '<td>' . $promozione['scadenza'] . '</td>'
                        . '<td>' . $promozione['luogo_di_fruizione'] . '</td>'
                        . '<td>' . $promozione['categoria'] . '</td>'
                        . '<td>' . $promozione['azienda'] . '</td>'
                        . '<td>' . $promozione['emissioni'] . '</td>'
                        . '<td>' . $immagine . '</td>';
            }?>
        </table>
        <br>
        <input class="btn btn-primary" type="submit" name="button"  value="Modifica/Cancella">
    </form>
</div>
