<div class="container">
    <br>
    <h3><b>Errore: sembra che tu abbia sbagliato ad inserire la vecchia password</b></h3>
    <br>
    <a class="btn btn-primary" href=" <?= $this->url(array(
                                    'controller' => 'staff',
                                    'action'     => 'formpassword',
                                    ), 
                                    'default',true); 
                                    ?>">Riprova</a>
    <a class="btn btn-primary" href=" <?= $this->url(array(
                                    'controller' => 'staff',
                                    'action'     => 'strumenti',
                                    ), 
                                    'default',true); 
                                    ?>">Torna alla pagina degli strumenti dello staff</a>
</div>


