<div class="container">
    <br>
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3><b>Modifica dati personali</b></h3>
            </div>
            <div class="panel-body">
                <div role="form">
                    <?= $this->datiForm; ?>
                    <a class="btn btn-primary" style="position: relative; left: 155px; bottom: 54px"
                       href=" <?= $this->url(array(
                                                    'controller' => 'staff',
                                                    'action'     => 'strumenti',
                                                    ), 
                                                    'default',true); 
                                                    ?>">Annulla</a>
                </div>
            </div>
        </div>
    </div>
</div>

