<div class="container">
    <br><br>
    <a class="btn btn-primary" href="<?= $this->url(array(
                                    'controller' => 'staff',
                                    'action'     => 'coupon',
                                    ), 
                                    'default',true); 
                                    ?>">< Promozioni</a><br>
    <h3><b>Modifica promozione</b></h3>
    <?= $this->couponModForm; ?>
    <br>
</div>

