<div class="container">
    <br>
    <h3><b>Modifica avvenuta con successo!</b></h3>
    <br>
    <br>
    <a class="btn btn-primary" href=" <?= $this->url(array(
                                    'controller' => 'user',
                                    'action'     => 'profilo',
                                    ), 
                                    'default',true); 
                                    ?>">Torna al tuo profilo</a>
    <a class="btn btn-primary" href=" <?= $this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'index',
                                    ), 
                                    'default',true); 
                                    ?>">Torna alla pagina degli strumenti staff</a>
</div>


