<div class="container">
    <br>
    <h3><b>Modifica avvenuta con successo!</b></h3>
    <br>
    <table class="table table-condensed">
        <tr><th style="text-align: center">ID</th><th>Nome</th><th>Descrizione</th><th>Inizio validità</th><th>Scadenza</th>
            <th>Luogo di fruizione</th><th>Categoria</th><th>Azienda</th><th>Tot. emissioni</th><th>Immagine</th>
            <?php
                $modificato = $this->modificato;
                if($modificato['immagine']==null){
                        $immagine = 'NON DISPONIBILE';
                }
                else{
                    $immagine = $modificato['immagine'];
                }
                echo '<tr><td style="text-align: center">' . $modificato['id'] . '</td>'
                        . '<td>' . $modificato['nome'] . '</td>'
                        . '<td>' . $modificato['descrizione'] . '</td>'
                        . '<td>' . $modificato['inizio_validita'] . '</td>'
                        . '<td>' . $modificato['scadenza'] . '</td>'
                        . '<td>' . $modificato['luogo_di_fruizione'] . '</td>'
                        . '<td>' . $modificato['categoria'] . '</td>'
                        . '<td>' . $modificato['azienda'] . '</td>'
                        . '<td style="text-align: center">' . $modificato['emissioni'] . '</td>'
                        . '<td>' . $immagine . '</td>';
            ?>
    </table>
    <br>
    <a class="btn btn-primary" href=" <?= $this->url(array(
                                    'controller' => 'staff',
                                    'action'     => 'coupon',
                                    ), 
                                    'default',true); 
                                    ?>">Modifica/cancella altre promozioni</a>
    <a class="btn btn-primary" href=" <?= $this->url(array(
                                    'controller' => 'staff',
                                    'action'     => 'index',
                                    ), 
                                    'default',true); 
                                    ?>">Torna alla pagina degli strumenti staff</a>
</div>


