<div class="static">
    <br>
    <h5>Registrazione promozione avvenuta con successo!</h5>
    <br>
    <ul>
        <li><a href=" <?= $this->url(array(
                                    'controller' => 'staff',
                                    'action'     => 'formcoupon',
                                    ), 
                                    'default',true); 
                                    ?>">Aggiungi altre promozioni</a>
        </li>
        <li><a href=" <?= $this->url(array(
                                    'controller' => 'staff',
                                    'action'     => 'index',
                                    ), 
                                    'default',true); 
                                    ?>">Torna alla pagina degli strumenti</a>
        </li>
    </ul>
</div>


