<div class="container">
    <br><br>
    <div class="row">
        <div class="col-md-6">
            <ul style="list-style-type:none">
                <h2>Gestione promozioni</h2>
                <li><a href="<?= $this->url(array(
                                        'controller' => 'staff',
                                        'action'     => 'formcoupon',
                                        ), 
                                        'default',true); 
                            ?>"><h4>Inserisci coupon</h4></a></li>
                <li><a href="<?= $this->url(array(
                                        'controller' => 'staff',
                                        'action'     => 'coupon',
                                        ), 
                                        'default',true); 
                            ?>"><h4>Modifica/cancella coupon</h4></a></li>
            </ul>
        </div>
        <div class="col-md-6">
            <ul style="list-style-type:none">
                <h2>Gestione profilo</h2>
                <li><a href="<?= $this->url(array(
                                        'controller' => 'staff',
                                        'action'     => 'formdati',
                                        ), 
                                        'default',true); 
                            ?>"><h4>Modifica dati personali</h4></a></li>
                <li><a href="<?= $this->url(array(
                                        'controller' => 'staff',
                                        'action'     => 'formpassword',
                                        ), 
                                        'default',true); 
                            ?>"><h4>Modifica password</h4></a></li>
            </ul>
        </div>
    </div>
</div>
<br><br>

