<div>
    <br><br>
    <ul>
        <fieldset>
            <legend>Gestione profilo</legend>
            <li>Gestisci informazioni profilo</li>
        </fieldset>
        <br><br>
        <fieldset>
            <legend>Gestione promozioni</legend>
            <li><a href="#">Inserisci coupon</a></li>
            <li><a href="#">Modifica/cancella coupon</a></li>
        </fieldset>
    </ul>
</div>

