<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbo2">
    <div class="container">
        <h1>Pagina delle Aziende</h1>
        <p>Ecco qua l'elenco completo delle aziende che hanno concesso sconti esclusivi per i nostri utenti!</p>
    </div>
</div>

<div class="container">
    <!-- Example row of columns -->
    <div class="row">
        <?php $i=1;
            foreach ($this->aziende as $azienda) :
            if($i%3 === 0){?>
            <div class="row">
            <?php } ?>
            <div class="col-md-4">
                <?php echo '<h2>' . $azienda->nome . '</h2>';
                echo $this->generalImg($azienda->immagine, 'aziende/' ,array('class' => 'imagefrm'));
                echo '<p>' . $this->text($azienda->descrizione) . '</p>';
                echo '<p><a class="btn btn-default" href='.$this->url(array(
                                        'controller' => 'public',
                                        'action'     => 'azienda',
                                        'selAzienda' => $azienda->id), 
                                        'default',true).'>
                                        Vedi i dettagli &raquo;</a></p>'; ?>
            </div>
            <?php if($i%3 === 0){?>
            </div> 
            <?php }
            $i++; endforeach ?>
    </div>
</div> 
<!-- /container --> 
