<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbo">
    <div class="col-lg-12">
    <?php $azienda=$this->azienda;
          echo '<p class="col-md-5">'.$this->generalImg($azienda->immagine,'aziende/' ,array('class' => 'img-circle')).'</p>';
          echo '<p class="col-md-7"> '
                .'<h2>' . $azienda->nome . '</h2>'.
                 '<p>' . $azienda->descrizione . '</p>'.'</p>';?>   
    </div>
</div>

<div class="container">
  <!-- Example row of columns -->
    <div class="row">
    <h3>Ecco tutti i coupon della azienda </h3>
        <?php foreach ($this->coupon as $coupon) {
            echo'<div class="col-md-4 style="padding-top:20px;">';
            echo $this->generalImg($coupon->immagine,'coupon/' ,array('class' => 'imagefrm'));
            echo '<h4>' .$coupon ->descrizione .' </h4>';
            echo '<p><a class="btn btn-default" href='.$this->url(array(
                                'controller' => 'public',
                                'action'     => 'coupon',
                                'selCoupon' => $coupon->id), 
                                'default',true).'>
                                Vedi i dettagli &raquo;</a></p>'; 
            echo'</div>';}?>
    </div>
    <hr>
</div>