<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbo">
    <div class="col-lg-12">
    <?php $cat=$this->categoria;
        echo '<p class="col-md-5">'.$this->generalImg($cat->immagine,'categorie/' ,array('class' => 'img-circle')).'</p>';
        echo '<p class="col-md-7"> '
              .'<h2>' . $cat->nome . '</h2>'.
               '<p>' . $cat->descrizione . '</p>'.'</p>';?>   
    </div>
</div>

<div class="container">
  <!-- Example row of columns -->
    <div class="row">
    <h3>Ecco tutti i coupon della categoria </h3>
        <?php $i=1;
            foreach ($this->coupon as $coupon) {
                if($i%3 === 0){
                echo '<div class="row">';
                }
                if($this->deadline($coupon->scadenza))
                {
                    if($i%3 === 0){
                        echo '<div class="row">';
                    }
                    echo'<div class="col-md-4 style="padding-top:20px;">';
                    echo $this->generalImg($coupon->immagine,'coupon/' ,array('class' => 'imagefrm'));
                    echo '<h4>' . $this->text($coupon ->descrizione) . ' </h4>';
                    echo '<p><a class="btn btn-default" href='.$this->url(array(
                                        'controller' => 'public',
                                        'action'     => 'coupon',
                                        'selCoupon' => $coupon->id), 
                                        'default',true).'>
                                        Vedi i dettagli &raquo;</a></p>';
                    echo'</div>';
                    if($i%3 === 0){
                        echo '</div>';  // end row
                    }
                }
                $i++;
            }?> 
    </div>
    <hr>
    <a class="btn btn-primary" role="button" href=" <?= $this->url(array(
                                                            'controller' => 'public',
                                                            'action'     => 'categorie',
                                                            ), 
                                                            'default',true); 
                                                            ?>">< Torna all'elenco categorie</a>
</div>