<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbo2">
    <div class="container">
        <h1>Pagina delle Categorie</h1>
        <p>Bla bla bla bla bla bla...</p>
    </div>
</div>

<div class="container">
    <!-- Example row of columns -->
    <div class="row">
        <?php $i=1;
        foreach ($this->categorie as $categoria) :
            if($i%3 === 0){?>
            <div class="row">
            <?php } ?>
            <div class="col-md-4">
                <?php echo '<h2>' . $categoria->nome . '</h2>';
                echo $this->generalImg($categoria->immagine, 'categorie/' ,array('class' => 'imagefrm'));
                echo '<p>' . $this->text($categoria->descrizione) . '</p>';
                echo '<p><a class="btn btn-default" href='.$this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'categoria',
                                    'selCategoria' => $categoria->id), 
                                    'default',true).'>
                                     Vedi i dettagli &raquo;</a></p>'; ?>
            </div>
            <?php if($i%3 === 0){?>
            </div> 
            <?php } ?>
        <?php $i++; endforeach ?>
    </div>
</div>

