<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
    <h1>Pagina del coupon</h1>
    <p>Breve descrizione del prodotto
    </p>
  </div>
</div>

<div class="container">
  <!-- Example row of columns -->
    <div class="row">
        <?php $coupon=$this->coupon  ?>
            <div class="col-md-12">
                <?php echo '<h2>' . $coupon->nome . '</h2>';
                echo $this->generalImg($coupon->immagine, 'coupon/', array('class' => 'imagefrm'));
                echo '<p>' . $coupon->descrizione . '</p>';
                switch ($this->authInfo('livello')){
                    case 'user':?>
                        <p><a class="btn btn-primary" role="button" target="_blank"  
                                href=" <?= $this->url(array(
                                              'controller' => 'public',
                                              'action'     => 'stampa',
                                              'selCoupon'  => $coupon->id
                                              ), 
                                              'default',true); 
                                              ?>">Stampa</a></p>
                    <?php break;
                    case 'admin':                    
                        break;
                    case 'staff':                    
                        break;
                    default : ?>
                        <br>
                        <h5><b>Per scaricare il coupon devi essere registrato</b></h5>
                        <p><a class="btn btn-primary"
                                href=" <?= $this->url(array(
                                              'controller' => 'public',
                                              'action'     => 'login',
                                              'selCoupon'  => $coupon->id
                                              ), 
                                              'default',true); 
                                              ?>">Login</a></p>
                        <p><a class="btn btn-primary" style="position: relative; left: 82px; bottom: 44px" 
                                href=" <?= $this->url(array(
                                              'controller' => 'public',
                                              'action'     => 'register',
                                              'selCoupon'  => $coupon->id
                                              ), 
                                              'default',true); 
                                              ?>">Registrati</a></p>
                    <?php break;
                    }?>
            </div>
	</div>
    <hr>
</div>