<?php $this->headScript()
 ->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
 ->appendFile($this->baseUrl('js/functionsButton.js'))
 ->captureStart() ?>

$(function()
{
    $("#stampa").on('click', function(event) {
        doRemove('stampa');
    });
});

<?php $this->headScript()->captureEnd() ?>
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <?php $coupon = $this->coupon;
            echo $this->generalImg($coupon->immagine,'coupon/' ,array('class' => 'img-responsive img-rounded imgcoupon'));?>
        </div>
        <!-- /.col-md-8 -->
        <div class="col-md-4">
            <?php
            echo '<h1>' . $coupon->nome . '</h1>';
            echo '<p>' . $coupon->descrizione . '</p><br>';
            switch ($this->authInfo('livello')){
                case 'user':
                    if($this->emesso !== 0){
                        echo '<h5><b>Coupon gi&agrave; scaricato</b></h5>';
                    }else{ ?>
                        <div id="stampa"
                            <p><a class="btn btn-primary btn-lg" role="button" target="_blank"  
                                    href=" <?= $this->url(array(
                                                  'controller' => 'user',
                                                  'action'     => 'stampa',
                                                  'selCoupon'  => $coupon->id
                                                  ), 
                                                  'default',true); 
                                                  ?>">Stampa il tuo coupon!</a></p>                        
                            <h5 style="color: #ff0000 "><b>N.B. NON CHIUDERE LA PAGINA CHE SI APRIR&Agrave;
                                    PRIMA DI AVERLA STAMPATA!</b></h5>
                        </div>
                <?php }?>
                <?php break;
                case 'admin':                    
                    break;
                case 'staff':                    
                    break;
                default : ?>
                    <h5><b>Per scaricare il coupon devi essere registrato</b></h5>
                    <p><a class="btn btn-primary"
                            href=" <?= $this->url(array(
                                          'controller' => 'public',
                                          'action'     => 'login',
                                          'selCoupon'  => $coupon->id
                                          ), 
                                          'default',true); 
                                          ?>">Login</a></p>
                    <p><a class="btn btn-primary" style="position: relative; left: 82px; bottom: 44px" 
                            href=" <?= $this->url(array(
                                          'controller' => 'public',
                                          'action'     => 'register',
                                          'selCoupon'  => $coupon->id
                                          ), 
                                          'default',true); 
                                          ?>">Registrati</a></p>
            <?php break;
            }?>
        </div>
        <!-- /.col-md-4 -->
    </div>
    <!-- /.row -->
    <hr>
    <!-- Content Row -->
    <div class="row">
        <div class="col-md-12">
            <h2>Informazioni del coupon</h2>
            <p><b>Azienda:</b>&emsp;
            <a href ="<?=$this->url(array(
                                  'controller' => 'public',
                                  'action'     => 'azienda',
                                  'selAzienda'  => $this->idAzienda
                                  ), 
                                  'default',true);?>"> <?= $this->azienda ?> </a></p>
            <p><b>Categoria:</b>&emsp;
            <a href ="<?=$this->url(array(
                                  'controller' => 'public',
                                  'action'     => 'categoria',
                                  'selCategoria'  => $this->idCategoria
                                  ), 
                                  'default',true);?>"> <?= $this->categoria ?> </a></p>
            <p><b>Valido dal:</b>&emsp;<?= $coupon->inizio_validita?></p>
            <p><b>Al:</b>&emsp;<?= $coupon->scadenza?></p>
            <p><b>Presso:</b>&emsp;<?= $coupon->luogo_di_fruizione?></p>
        </div>
    </div>
    <hr>
    <a class="btn btn-primary" role="button" href="<?=$this->url(array(
                                  'controller' => 'public',
                                  'action'     => 'azienda',
                                  'selAzienda'  => $this->idAzienda
                                  ), 
                                  'default',true);?>">< Torna a: <?=$this->azienda?></a>
    <a class="btn btn-primary" role="button" style="position: relative; left: 20px;"
       href = "<?=$this->url(array(
                                  'controller' => 'public',
                                  'action'     => 'categoria',
                                  'selCategoria'  => $this->idCategoria
                                  ), 
                                  'default',true);?>">< Torna a: <?=$this->categoria?></a>
</div>
