<header id="myCarousel" class="carousel slide">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item active">
            <div class="fill" style="background-image:url('../../public/images/zymil.jpg');"></div>
            <div class="carousel-caption">
                <h2>Offerta Zymil</h2>
            </div>
        </div>
        <div class="item">
            <div class="fill" style="background-image:url('../../public/images/adidas.jpg');"></div>
            <div class="carousel-caption">
                <h2>Codice sconto 15% ADIDAS</h2>
            </div>
        </div>
        <div class="item">
            <div class="fill" style="background-image:url('../../public/images/coop.jpg');"></div>
            <div class="carousel-caption">
                <h2>Stampa buono Coop da 5 euro</h2>
            </div>
        </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="icon-next"></span>
    </a>
</header>

<!-- Page Content -->
<div class="container">

    <!-- Marketing Icons Section -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Benvenuto in Coupon is Life!
            </h1>
        </div>
        <div class="col-md-6">
            <p>La piattaforma per ricevere coupon a tutto spiano!</p>
            <ul>
                <li><strong>Varie categorie prensenti nel sito:</strong>
                </li>
                <li>Sconti su smartphone</li>
                <li>Sconti su abbigliamento</li>
                <li>Sconti per la casa</li>
                <li>Sconti per la scuola</li>
            </ul>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis,
            omnis doloremque non cum id reprehenderit, quisquam totam aspernatur
            tempora minima unde aliquid ea culpa sunt. Reiciendis quia dolorum ducimus unde.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, omnis
            doloremque non cum id reprehenderit, quisquam totam aspernatur tempora minima
            unde aliquid ea culpa sunt. Reiciendis quia dolorum ducimus unde.</p>
        </div>
        <div class="col-md-6">
            <div class="panel panel-info" >
                <div class="panel-heading">
                    <div class="panel-title">Login</div>
                </div>     

                <div style="padding-top:30px" class="panel-body" >

                    <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>

                    <form id="loginform" class="form-horizontal" role="form">

                        <div style="margin-bottom: 25px" class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            <input id="login-username" type="text" class="form-control" name="username" value="" placeholder="username o email">                                        
                        </div>

                        <div style="margin-bottom: 25px" class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                            <input id="login-password" type="password" class="form-control" name="password" placeholder="password">
                        </div>



                        <div style="margin-top:10px" class="form-group">
                            <!-- Button -->
                            <div class="col-sm-12 controls">
                                <a id="btn-login" href="#" class="btn btn-success">Login</a>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12 control">
                                <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
                                    Non hai un account?
                                <a href="<?= $this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'logreg'), 
                                    'default',true); 
                                    ?>">Registrati qui</a>
                                </div>
                            </div>
                        </div>    
                    </form>     



                </div>                     
            </div>  
        </div>
    </div>
    <!-- /.row -->

    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h4 class="text-center" id="grandangolari-spinti">Aziende pi&ugrave; popolari</h4>
                </div>
                <div class="panel-body text-center">
                    <p class="lead">
                    <div class="panel-heading">
                        <span class="fa-stack fa-5x">
                              <i class="fa fa-circle fa-stack-2x text-primary"></i>
                              <i class="fa fa-home fa-stack-1x fa-inverse"></i>
                        </span>
                    </div>
                    </p>
                </div>
                <ul class="list-group list-group-flush text-center">
                    <li class="list-group-item">
                        <a href="#" title="Fileni">Fileni</a>
                    </li>
                    <li class="list-group-item">
                        <a href="#" title="Baldi carni">Baldi carni</a>
                    </li>
                    <li class="list-group-item">
                        <a href="#" title="Uci Cinemas">Uci Cinemas</a>
                    </li>
                    <li class="list-group-item">
                        <a href="#" title="Coltorti">Coltorti</a>
                    </li>
                    <li class="list-group-item">
                        <a href="#" title="Jammin">Jammin</a>
                    </li>
                    <li class="list-group-item">
                       <a href="#" title="Barchiesi sport">Barchiesi sport</a>
                    </li>
                </ul>
                <div class="panel-footer">
                    <a href="<?= $this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'aziende'), 
                                    'default',true); 
                            ?>"
                            class="btn btn-lg btn-block btn-primary" >Vai alla pagina delle Aziende</a>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h4 class="text-center" id="grandangolari-spinti">Categorie pi&ugrave; popolari</h4>
                </div>
                <div class="panel-body text-center">
                    <p class="lead">
                    <div class="panel-heading">
                        <span class="fa-stack fa-5x">
                              <i class="fa fa-circle fa-stack-2x text-primary"></i>
                              <i class="fa fa-sitemap fa-stack-1x fa-inverse"></i>
                        </span>
                    </div>
                    </p>
                </div>
                <ul class="list-group list-group-flush text-center">
                    <li class="list-group-item">
                        <a href="#" title="Fileni">Elettronica</a>
                    </li>
                    <li class="list-group-item">
                        <a href="#" title="Baldi carni">Per la casa</a>
                    </li>
                    <li class="list-group-item">
                        <a href="#" title="Uci Cinemas">Sport</a>
                    </li>
                    <li class="list-group-item">
                        <a href="#" title="Coltorti">Informatica</a>
                    </li>
                    <li class="list-group-item">
                        <a href="#" title="Hobby">Hobby</a>
                    </li>
                    <li class="list-group-item">
                       <a href="#" title="Per la scuola">Per la scuola</a>
                    </li>
                </ul>
                <div class="panel-footer">
                    <a class="btn btn-lg btn-block btn-primary">Vai alla pagina delle Categorie</a>
                </div>
            </div>
        </div>
    </div>

    <div class="row"> 

        <div id="myCarousel2" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel2" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel2" data-slide-to="1"></li>
                <li data-target="#myCarousel2" data-slide-to="2"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                <div class="item active">
                <img src="../../public/images/nike.jpg" alt="nike" style="width: 1280px;height: 400px;">
                    <div class="carousel-caption">
                        <h2>Nike super offerta</h2>
                    </div>
                </div>

                <div class="item">
                    <img src="../../public/images/mediaworld.jpg" alt="mediaworld"  style="width: 1280px;height: 400px;">
                    <div class="carousel-caption">
                        <h2>Smartphone 50% da Mediaworld</h2>
                    </div>
                </div>

                <div class="item">
                    <img src="../../public/images/zalando.jpg" alt="zalando" style="width: 1280px;height: 400px;">
                    <div class="carousel-caption">
                        <h2>Offerta Zalando</h2>
                    </div>
                </div>
            </div>

            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel2" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel2" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>
<!-- /.container -->