<h3 style="text-align:center; margin-top:15px; margin-bottom:0px; color: #337ab7">
    <i class="fa fa-arrow-down" aria-hidden="true"></i>
    &nbsp; Più recenti &nbsp;<i class="fa fa-arrow-down" aria-hidden="true"></i></h3>
<header id="myCarousel" class="carousel slide" style="margin-top: 11px;">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    
    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <?php $count=0;
        foreach($this->coupon as $coupon){
        $variab = $this->Slider($coupon->inizio_validita, $coupon->immagine);
            if($variab!==false && $count<3){
                echo '<a id="oggetto" class="item" href='.$this->url(array(
                                        'controller' => 'public',
                                        'action'     => 'coupon',
                                        'selCoupon' => $coupon->id), 
                                        'default',true).'>';
                echo "<script>";
                echo "$('#oggetto').removeClass('item');";
                echo "$('#oggetto').addClass('item active');"; 
                echo "</script>"; 
                echo $this->generalImg($variab,'coupon/',array('class'=>'fill'));
                     $count++;
                echo '</a>';
            }
        } ?>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="icon-next"></span>
    </a>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js">
    </script>
</header>

<!-- Page Content -->
<div class="container">

    <!-- Marketing Icons Section -->
    <div class="row">
        <div  id="titolo" class="col-md-8">
            <h1 class="page-header">Benvenuto in Coupon is Life!</h1><br>
            <h4 id="par" >La piattaforma per ricevere coupon a tutto spiano!
            <br>
            <br>
            Nel nostro sito potrai ottenere degli sconti favolosi per i tuoi acquisti!Basta che ti registri per poi accedere con le tue credenziali in maniera del tutto gratuita! Dopodichè potrai effettuare una ricerca per trovare il prodotto dei tuoi sogni a prezzi assurdi! Per qualsiasi dubbio che ti verrà puoi visitare le nostre FAQ,altrimenti puoi contattarci in ogni momento tramite e-mail. Saremo felici di aiutarti!Cerchiamo ogni giorno nuovi partner commerciali in modo da poterti dare una scelta sempre più amplia di prodotti in offerta! Che aspetti? Entra a far parte di Coupon is Life!
            </h4>
        </div>
        <div class="col-md-4" id="login-form">
            <br><br>
            <div class="panel panel-info" >
                <div class="panel-heading">
                    <div class="panel-title">Login</div>
                </div>     

                <div style="text-align:center; padding-top:30px" class="panel-body">

                    <div style="display:none" id="login-alert"\.
                         class="alert alert-danger col-sm-12"></div>
                    
                    <?php
                        switch ($this->authInfo('livello')){
                            case 'user':?>
                            <script type="text/javascript">
                                $('#login-form').remove();
                                $('#titolo').toggleClass('col-md-8','col-md-12');
                                $('#par').addClass('col-md-12');
                                $('#par').text('Complimenti ora sei loggato e puoi ottenere qualsiasi coupon presente nel nostro catalogo!');
                            </script>

                    <?php break;
                            case 'staff':?>
                            <script type="text/javascript">
                                $('#login-form').remove();
                                $('#titolo').toggleClass('col-md-8','col-md-12');
                                $('#par').addClass('col-md-12');
                                $('#par').text('Benvenuto membro dello staff! Ora puoi gestire le promozioni dedicate ai clienti!');
                            </script>
                    <?php break;
                            case 'admin':?>
                            <script type="text/javascript">
                                $('#login-form').remove();
                                $('#titolo').toggleClass('col-md-8','col-md-12');
                                $('#par').addClass('col-md-12');
                                $('#par').text('Benvenuto amministratore! Puoi navigare nel sito o in alternativa gestirlo tramite il menù apposito.')
                            </script>

                    <?php break;
                            default:
                                echo $this->loginForm;
                            break;                                 
                        }?>
                    <br> 
                    <div class="col-md-12 control">
                        <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
                            Non hai un account?
                        <a href="<?= $this->url(array(
                            'controller' => 'public',
                            'action'     => 'register'), 
                            'default',true); 
                            ?>">Registrati qui</a>
                        </div>
                    </div>
                </div>                     
            </div>
        </div>
    </div>
    <br>
    <br>
    <!-- /.row -->

    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h4 class="text-center" id="grandangolari-spinti">Aziende pi&ugrave; popolari</h4>
                </div>
                <div class="panel-body text-center">
                    <p class="lead">
                    <div class="panel-heading">
                        <span class="fa-stack fa-5x">
                              <i class="fa fa-circle fa-stack-2x text-primary"></i>
                              <a href="<?= $this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'aziende'), 
                                    'default',true); 
                            ?>"
                            class="fa fa-home fa-stack-1x fa-inverse" ></a>
                        </span>
                    </div>
                    </p>
                </div>
                <ul class="list-group list-group-flush text-center">
                    <?php for($j=0;$j<5;$j++) :?>
                    <?php if(!empty($this->aziende[$j])){
                        echo '<li class="list-group-item">';
                        $azienda=$this->aziende[$j];
                        echo'<a href='.$this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'azienda',
                                    'selAzienda' => $azienda->id), 
                                    'default',true). 
                             '>'. $azienda->nome .'</a>';}
                        echo '</li>'; ?>
                    <?php endfor ?>        
                </ul>
                <div class="panel-footer">
                    <a href="<?= $this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'aziende'), 
                                    'default',true); 
                            ?>"
                            class="btn btn-lg btn-block btn-primary" >Vai alla pagina delle Aziende</a>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h4 class="text-center" id="grandangolari-spinti">Categorie pi&ugrave; popolari</h4>
                </div>
                <div class="panel-body text-center">
                    <p class="lead">
                    <div class="panel-heading">
                        <span class="fa-stack fa-5x">
                              <i class="fa fa-circle fa-stack-2x text-primary"></i>
                               <a href="<?= $this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'categorie'), 
                                    'default',true); 
                                ?>" class="fa fa-sitemap fa-stack-1x fa-inverse"></a>
                        </span>
                    </div>
                    </p>
                </div>
                <ul class="list-group list-group-flush text-center">
                    <?php for($i=0;$i<5;$i++) :?>
                    <?php if(!empty($this->categorie[$i])){
                        echo '<li class="list-group-item">';
                        $categoria=$this->categorie[$i];
                        echo'<a href='.$this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'categoria',
                                    'selCategoria' => $categoria->id), 
                                    'default',true)
                            .'>'. $categoria->nome .'</a>';}
                        echo '</li>'; ?>
                    <?php endfor ?> 
                </ul>
                <div class="panel-footer">
                    <a <a href="<?= $this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'categorie'), 
                                    'default',true); 
                            ?>" class="btn btn-lg btn-block btn-primary">Vai alla pagina delle Categorie</a>
                </div>
            </div>
        </div>
    </div>

    <div class="row"> 

        <div id="myCarousel2" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel2" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel2" data-slide-to="1"></li>
                <li data-target="#myCarousel2" data-slide-to="2"></li>
            </ol>

            <!-- Wrapper for slides -->

            <div class="carousel-inner">
                <?php $conto=0;?>
                <?php foreach($this->coup as $coup) :?>
                <?php $var=$this->Slider((int)$coup->emissioni,$coup->immagine);
                    if($var!==false && $conto<3){
                    echo '<a id="oggetto2" class="item" href='.$this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'coupon',
                                    'selCoupon' => $coup->id), 
                                    'default',true).'>';
                    echo "<script>";
                    echo "$('#oggetto2').removeClass('item');";
                    echo "$('#oggetto2').addClass('item active');"; 
                    echo "</script>"; 
                    echo $this->generalImg($var,'coupon/',array('class'=>'miaclasse'));
                         $conto++;
                    echo '</a>'; } ?>
                <?php endforeach ?>
            </div>
            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel2" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel2" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        <h3 style="text-align:center; margin-top:15px; margin-bottom:0px; color: #337ab7">
            <i class="fa fa-arrow-up" aria-hidden="true"></i> &nbsp; Più popolari &nbsp;
            <i class="fa fa-arrow-up" aria-hidden="true"></i></h3>
    </div>
</div>
<!-- /.container -->