<header id="myCarousel" class="carousel slide">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    
    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <?php $count=0;?>
        <?php foreach($this->coupon as $coupon) :?>
        <?php $variab=$this->Slider($coupon->inizio_validita,$coupon->immagine);
            if($variab!==false && $count<3){
            echo '<a id="oggetto" class="item" href='.$this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'coupon',
                                    'selCoupon' => $coupon->id), 
                                    'default',true).'>';
            echo "<script>";
            echo "$('#oggetto').removeClass('item');";
            echo "$('#oggetto').addClass('item active');"; 
            echo "</script>"; 
            echo $this->generalImg($variab,'coupon/',array('class'=>'fill'));
                 $count++;
            echo '</a>'; } ?>
        <?php endforeach ?>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="icon-next"></span>
    </a>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js">
    </script>
</header>

<!-- Page Content -->
<div class="container">

    <!-- Marketing Icons Section -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Benvenuto in Coupon is Life!</h1>
        </div>
        <div class="col-md-6">
            <p>La piattaforma per ricevere coupon a tutto spiano!</p>
            <ul>
                <li><strong>Varie categorie prensenti nel sito:</strong>
                </li>
                <li>Sconti su smartphone</li>
                <li>Sconti su abbigliamento</li>
                <li>Sconti per la casa</li>
                <li>Sconti per la scuola</li>
            </ul>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis,
            omnis doloremque non cum id reprehenderit, quisquam totam aspernatur
            tempora minima unde aliquid ea culpa sunt. Reiciendis quia dolorum ducimus unde.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, omnis
            doloremque non cum id reprehenderit, quisquam totam aspernatur tempora minima
            unde aliquid ea culpa sunt. Reiciendis quia dolorum ducimus unde.</p>
        </div>
        <div class="col-md-6" id="login-form">
            <div class="panel panel-info" >
                <div class="panel-heading">
                    <div class="panel-title">Login</div>
                </div>     

                <div style="padding-top:30px" class="panel-body" >

                    <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
                    
                    <?php
                        switch ($this->authInfo('livello')){
                            case 'user':?>
                            <script type="text/javascript">
                                $('#login-form').remove();
                                $('#par').toggleClass('col-md-6','col-md-12');
                            </script>

                    <?php break;
                            case 'staff':?>
                            <script type="text/javascript">
                                $('#login-form').remove();
                                $('#par').toggleClass('col-md-6','col-md-12');
                            </script>
                    <?php break;
                            case 'admin':?>
                            <script type="text/javascript">
                                $('#login-form').remove();
                                $('#par').toggleClass('col-md-6','col-md-12');
                            </script>

                    <?php break;
                            default:
                            echo $this->loginForm;
                            break;                                 
                        }?>
                            
                    <div class="col-md-12 control">
                        <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
                            Non hai un account?
                        <a href="<?= $this->url(array(
                            'controller' => 'public',
                            'action'     => 'register'), 
                            'default',true); 
                            ?>">Registrati qui</a>
                        </div>
                    </div>
                </div>                     
            </div>
        </div>
    </div>
    <!-- /.row -->

    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h4 class="text-center" id="grandangolari-spinti">Aziende pi&ugrave; popolari</h4>
                </div>
                <div class="panel-body text-center">
                    <p class="lead">
                    <div class="panel-heading">
                        <span class="fa-stack fa-5x">
                              <i class="fa fa-circle fa-stack-2x text-primary"></i>
                              <i class="fa fa-home fa-stack-1x fa-inverse"></i>
                        </span>
                    </div>
                    </p>
                </div>
                <ul class="list-group list-group-flush text-center">
                    <?php for($j=0;$j<5;$j++) :?>
                    <?php if(!empty($this->aziende[$j])){
                        echo '<li class="list-group-item">';
                        $azienda=$this->aziende[$j];
                        echo'<a href='.$this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'azienda',
                                    'selAzienda' => $azienda->id), 
                                    'default',true). 
                             '>'. $azienda->nome .'</a>';}
                        echo '</li>'; ?>
                    <?php endfor ?>        
                </ul>
                <div class="panel-footer">
                    <a href="<?= $this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'aziende'), 
                                    'default',true); 
                            ?>"
                            class="btn btn-lg btn-block btn-primary" >Vai alla pagina delle Aziende</a>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h4 class="text-center" id="grandangolari-spinti">Categorie pi&ugrave; popolari</h4>
                </div>
                <div class="panel-body text-center">
                    <p class="lead">
                    <div class="panel-heading">
                        <span class="fa-stack fa-5x">
                              <i class="fa fa-circle fa-stack-2x text-primary"></i>
                              <i class="fa fa-sitemap fa-stack-1x fa-inverse"></i>
                        </span>
                    </div>
                    </p>
                </div>
                <ul class="list-group list-group-flush text-center">
                    <?php for($i=0;$i<5;$i++) :?>
                    <?php if(!empty($this->categorie[$i])){
                        echo '<li class="list-group-item">';
                        $cat=$this->categorie[$i];
                        echo'<a href='.$this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'categoria',
                                    'selCat' => $cat->id), 
                                    'default',true)
                            .'>'. $cat->nome .'</a>';}
                        echo '</li>'; ?>
                    <?php endfor ?> 
                </ul>
                <div class="panel-footer">
                    <a <a href="<?= $this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'categorie'), 
                                    'default',true); 
                            ?>" class="btn btn-lg btn-block btn-primary">Vai alla pagina delle Categorie</a>
                </div>
            </div>
        </div>
    </div>

    <div class="row"> 

        <div id="myCarousel2" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel2" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel2" data-slide-to="1"></li>
                <li data-target="#myCarousel2" data-slide-to="2"></li>
            </ol>

            <!-- Wrapper for slides -->

            <div class="carousel-inner">
                <?php $conto=0;?>
                <?php foreach($this->coup as $coup) :?>
                <?php $var=$this->Slider((int)$coup->emissioni,$coup->immagine);
                    if($var!==false && $conto<3){
                    echo '<a id="oggetto2" class="item" href='.$this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'coupon',
                                    'selCoupon' => $coup->id), 
                                    'default',true).'>';
                    echo "<script>";
                    echo "$('#oggetto2').removeClass('item');";
                    echo "$('#oggetto2').addClass('item active');"; 
                    echo "</script>"; 
                    echo $this->generalImg($var,'coupon/',array('class'=>'miaclasse'));
                         $conto++;
                    echo '</a>'; } ?>
                <?php endforeach ?>
            </div>


            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel2" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel2" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>
<!-- /.container -->