<!-- Page Content -->
<div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Accedi o registrati
            </h1>
        </div>
    </div>
    <!-- /.row -->

    <!-- Content Row -->
    <div class="row">
        <div class="col-lg-12">
			<div class="static">
			 <h3>Login</h3>
			 <p>Utilizza questa form per l'autenticazione</p>
			 <?php echo $this->loginForm; ?>
			 <h5>se non hai ancora un account</h5>
			 <h3>Registrati</h3>
			 <?php echo $this->registrazioneForm; ?>
			</div>

        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <hr>
</div>
<!-- /.container -->