<div class="container">
    <br>
    <h3><b>Registrazione avvenuta con successo!</b></h3>
    <br>
    <a class="btn btn-primary" href=" <?= $this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'index',
                                    ), 
                                    'default',true); 
                                    ?>">Torna alla homepage</a>
    <a class="btn btn-primary" href=" <?= $this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'login',
                                    ), 
                                    'default',true); 
                                    ?>">Vai alla pagina di login</a>
</div>

