<div class="static">
    <br>
    <h5>Registrazione avvenuta con successo!</h5>
    <br>
    <a href=" <?= $this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'index',
                                    ), 
                                    'default',true); 
                                    ?>">Torna alla homepage</a>
</div>

