<br/>
<br/>

<div class="container" style="text-align:center;">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h1>Registrati</h1>
                </div>
                <div class="panel-body">
                    <div role="form">

                           <?php echo $this->userForm; ?>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>