<!-- Page Content -->
<div class="container">
    <!-- Page Heading/Breadcrumbs -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Risultati della ricerca</h1>
        </div>
    </div>
    <b>Abbiamo trovato:</b>
    <p id="notfound"> Nessun risultato </p>
    <!-- /.row -->

    <!-- Content Row -->
    <div class="row">
        <div class="panel-group" id="accordion">
            <p>  
            <?php
            $filtro = $this->filtro;
            //$risultati = $this->risultati;  //filtra in base a ciò che scegli o Categorie o Coupon
            //$categorieTrovate = $this->risultati1; //Entrambe trova le CATEGORIE
            //$couponTrovati = $this->risultati2; //Entrambe trova i COUPON
            if(!$this->risultati=="") {
                $i=1;
                foreach ($this->risultati as $risultati) 
                {   
                    if($this->deadline($risultati->scadenza)){
                        //in base alla scelta del filtro
                        if($i%3 === 0){
                        echo '<div class="row">';
                        }
                        echo '<div class="col-md-4">' ;
                        echo '<h2>' . $risultati->nome . '</h2>';
                        if($filtro=="categoria")
                        {
                            echo $this->generalImg($risultati->immagine,'categorie/' ,array('class' => 'imagefrm'));
                            echo '<p>' . $this->text($risultati->descrizione) . '</p>';
                            echo '<p><a class="btn btn-default" href='.$this->url(array(
                                'controller' => 'public',
                                'action'     => 'categoria',
                                'selCategoria' => $risultati->id), 
                                'default',true).'>
                                Vedi i dettagli &raquo;</a></p>'; 
                        }else{
                            echo $this->generalImg($risultati->immagine,'coupon/' ,array('class' => 'imagefrm'));
                            echo '<p>' . $this->text($risultati->descrizione) . '</p>';
                            echo '<p><a class="btn btn-default" href='.$this->url(array(
                                'controller' => 'public',
                                'action'     => 'coupon',
                                'selCoupon' => $risultati->id), 
                                'default',true).'>
                                 Vedi i dettagli &raquo;</a></p>';
                        }
                        echo '</div>';
                        if($i%3 === 0){
                        echo '</div>';
                        }
                        echo "<script>";
                        echo "$(document).ready(function(){ 
                            $('#notfound').hide(); });";
                        echo "</script>";
                        $i++;
                    }
                }
            }else if(!$this->risultati1=="" && !$this->risultati2=="")
            {   
                $i=1;
                foreach ($this->risultati1 as $categorieTrovate) 
                {
                    //entrambe
                    if($i%3 === 0){
                    echo '<div class="row">';
                    }
                    echo '<div class="col-md-4">' ;    
                    echo '<h2>' . $categorieTrovate->nome . '</h2>';
                    echo $this->generalImg($categorieTrovate->immagine,'categorie/' ,array('class' => 'imagefrm'));
                    echo '<p>' . $this->text($categorieTrovate->descrizione) . '</p>';
                    echo '<p><a class="btn btn-default" href='.$this->url(array(
                        'controller' => 'public',
                        'action'     => 'categoria',
                        'selCategoria' => $categorieTrovate->id), 
                        'default',true).'>
                         Vedi i dettagli &raquo;</a></p>'; 
                    echo '</div>';
                    if($i%3 === 0){
                    echo '</div>';
                    }
                    echo "<script>";
                    echo "$(document).ready(function(){ 
                    $('#notfound').hide(); });";
                    echo "</script>";
                    $i++;
                }
                foreach ($this->risultati2 as $couponTrovati) 
                {
                    if($this->deadline($couponTrovati->scadenza)){
                        //entrambe
                        if($i%3 === 0){
                        echo '<div class="row">';
                        }
                        echo '<div class="col-md-4">' ;  
                        echo '<h2>' . $couponTrovati->nome . '</h2>';
                        echo $this->generalImg($couponTrovati->immagine,'coupon/' ,array('class' => 'imagefrm'));
                        echo '<p>' . $this->text($couponTrovati->descrizione) . '</p>';
                        echo '<p><a class="btn btn-default" href='.$this->url(array(
                            'controller' => 'public',
                            'action'     => 'coupon',
                            'selCoupon' => $couponTrovati->id), 
                            'default',true).'>
                             Vedi i dettagli &raquo;</a></p>'; 
                        echo '</div>';
                        if($i%3 === 0){
                        echo '</div>';
                        }
                        echo "<script>";
                        echo "$(document).ready(function(){ 
                        $('#notfound').hide(); });";
                        echo "</script>";
                        $i++;
                    }
                }
            }
            ?>
            </p>
        </div>
    </div>
    <hr>
    <!-- /.panel-group -->
    <!-- /.col-lg-12 -->
</div>