<!-- Page Content -->
<div class="container">
    <!-- Page Heading/Breadcrumbs -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Risultati della ricerca
            </h1>
        </div>
    </div>
    <b>Abbiamo trovato:</b>
    <p id="notfound"> Nessun risultato </p>
    <!-- /.row -->

    <!-- Content Row -->
    <div class="row">

            <div class="panel-group" id="accordion">
                <p>
                   
                     <!--<div class="col-md-4"> -->
                      
                     <?php

                              $ris =$this->risultati;  //si occupa di filtrare sia per l'option categoria che coupon 
                              $ris1 =$this->risultati1; // entrambe - per appoggiarmi il valore di cat
                              $ris2 =$this->risultati2; // entrambe - per appoggiarmi il valore di coupon

                              if(!$ris=="") {

                                foreach ($this->risultati as $ris) 
                                {

                                    echo '<div class="col-md-4">' ;
                                    echo '<h2>' . $ris->nome . '</h2>';
                                    echo '<img src="/../../public/img/Logo_Fileni.jpg" width="300" height="150">';
                                    echo '<p>' . $ris->descrizione . '</p>';
                                    echo '<p><a class="btn btn-default" href="#" role="button">Vedi i dettagli &raquo;</a></p>';
                                    echo '</div>';
                                      echo "<script>";
                                      echo "$(document).ready(function(){ 
                                        $('#notfound').hide(); });";
                                      echo "</script>";

                                     }
                                }
                                else if(!$ris1=="" && !$ris2=="") {


                                foreach ($this->risultati1 as $ris1) 
                                {
                                    echo '<div class="col-md-4">' ;    
                                    echo '<h2>' . $ris1->nome . '</h2>';
                                    echo '<img src="/../../public/img/Logo_Fileni.jpg" width="300" height="150">';
                                    echo '<p>' . $ris1->descrizione . '</p>';
                                    echo '<p><a class="btn btn-default" href="#" role="button">Vedi i dettagli &raquo;</a></p>';
                                    echo '</div>';
                                    echo "<script>";
                                    echo "$(document).ready(function(){ 
                                    $('#notfound').hide(); });";
                                    echo "</script>";
                                }
                                foreach ($this->risultati2 as $ris2) 
                                {

                                    echo '<div class="col-md-4">' ;  
                                    echo '<h2>' . $ris2->nome . '</h2>';
                                    echo '<img src="/../../public/img/Logo_Fileni.jpg" width="300" height="150">';
                                    echo '<p>' . $ris2->descrizione . '</p>';
                                    echo '<p><a class="btn btn-default" href="#" role="button">Vedi i dettagli &raquo;</a></p>';
                                    echo '</div>';

                                }

                                

                              }


                              
                      ?>
              
                     
                </div>

                </p>

            </div>
            <!-- /.panel-group -->
        <!--</div>-->
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <hr>
</div>
<!-- /.container -->