<!-- Nav -->
<nav class="navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Logo e toggle x mobile -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?= $this->url(array(
                                'controller' => 'public',
                                'action'     => 'index',
                                ), 
                                'default',true); 
                                ?>">Coupon is Life</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href=" <?= $this->url(array(
                                'controller' => 'public',
                                'action'     => 'index'
                                ), 
                                'default',true); 
                                ?>">Home</a>
                </li>
                <li>
                    <a href="<?= $this->url(array(
                                'controller' => 'public',
                                'action'     => 'aziende'), 
                                'default',true); 
                                ?>">Aziende</a>
                </li>
                <li class="dropdown">
                    <a href="<?= $this->url(array(
                                'controller' => 'public',
                                'action'     => 'categorie'), 
                                'default',true); 
                                ?>" class="dropdown-toggle" >Categorie <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>                             
                            <?php
                            $guestModel = new Application_Model_Guest();
                            $categorie = $guestModel->getCategorie();
                            foreach ($categorie as $categoria)
                            {
                                echo '<li>';
                                echo '<a href='. $this->url(array(
                                    'controller' => 'public',
                                    'action' => 'categoria',
                                    'selCategoria' => $categoria->id),
                                    'default', true)
                                .'>'. $categoria->nome .'</a>';
                                echo '</li>';
                            }?>                             
                        </li>                       
                    </ul>
                </li>
                <li>
                    <a href=" <?= $this->url(array(
                                'controller' => 'public',
                                'action'     => 'faq'),
                                'default',true);
                                ?>">FAQ</a>
                </li>
                <?php
                    switch ($this->authInfo('livello')){
                        case 'user':?>
                        <li>
                            <a href="<?= $this->url(array(
                                'controller' => 'user',
                                'action'     => 'profilo'), 
                                'default',true); 
                                ?>">Gestione Profilo</a>
                        </li>
                        <li>
                            <a href="<?= $this->url(array(
                                        'controller' => 'user',
                                        'action'     => 'logout'), 
                                        'default',true); 
                                        ?>">Logout</a>
                        </li>
                        <?php break;

                        case 'staff':?>
                        <li>
                            <a href="<?= $this->url(array(
                                'controller' => 'staff',
                                'action'     => 'strumenti'), 
                                'default',true); 
                                ?>">Strumenti Staff</a>
                        </li>
                        <li>
                            <a href="<?= $this->url(array(
                                        'controller' => 'staff',
                                        'action'     => 'logout'), 
                                        'default',true); 
                                        ?>">Logout</a>
                        </li>
                        <?php break;

                        case 'admin':?>
                        <li>
                            <a href="<?= $this->url(array(
                                'controller' => 'admin',
                                'action'     => 'amministrazione'), 
                                'default',true); 
                                ?>">Strumenti Amministratore</a>
                        </li>
                        <li>
                            <a href="<?= $this->url(array(
                                        'controller' => 'user',
                                        'action'     => 'logout'), 
                                        'default',true); 
                                        ?>">Logout</a>
                        </li>
                        <?php break;

                        default:?>
                        <li>
                            <a href="<?= $this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'login'), 
                                    'default',true); 
                                    ?>">Login</a>
                        </li>
                        <li>
                            <a href="<?= $this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'register'), 
                                    'default',true); 
                                    ?>">Registrati</a>
                        </li>
                    <?php
                        break;
                        }?>
            </ul>

            <!--INIZIO BARRA DI RICERCA -->
            <form method="post" action="<?= $this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'ricerca'), 
                                    'default',true); 
                                    ?>">
            <div class="input-group" style="padding-top:8px; margin-bottom:10px;" >
                <div class="input-group-btn search-panel">

                <select name="filtro" class="form-control" style="width:150px;">
                    <option value="entrambe">>>Entrambe</option>
                    <option value="categoria">>>Categoria</option>
                    <option value="coupon">>>Coupon</option>  
                </select>

                </div>

               <!--<input type="hidden" name="search_param" value="name" id="search_param"> -->        
                <input type="text" class="form-control" name="testo" placeholder="Sconto nike, Unieuro coupon 2017.." id="search_key" value="">
                <span class="input-group-btn">
                        <!--<a class="btn btn-default text-muted" href="" title="Clear"><i class="glyphicon glyphicon-remove"></i> </a>-->
                        <button class="btn btn-info" type="submit">  Cerca!  </button> 
                       <!-- <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                </span>
            </div>-->
            </form>
               <!--FINE BARRA DI RICERCA 

        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>
