    <!-- Nav -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Logo e toggle x mobile -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?= $this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'index',
                                    ), 
                                    'default',true); 
                                    ?>">Coupon is Life</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href=" <?= $this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'index'
                                    ), 
                                    'default',true); 
                                    ?>">Home</a>
                    </li>
                    <li>
                        <a href=" <?= $this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'viewstatic',
                                    'staticPage' => 'faq'), 
                                    'default',true); 
                                    ?>">FAQ</a>
                    </li>
                    <li>
                        <a href="<?= $this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'aziende'), 
                                    'default',true); 
                                    ?>">Aziende</a>
                    </li>
                    <li class="dropdown">
                        <a href="<?= $this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'categorie'), 
                                    'default',true); 
                                    ?>" class="dropdown-toggle" data-toggle="dropdown">Categorie <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="<?= $this->url(array(
                                    'controller' => 'public',
                                    'action'     => 'categorie'), 
                                    'default',true); 
                                    ?>">Elettronica</a>
                            </li>
                            <li>
                                <a href="#">Informatica</a>
                            </li>
                            <li>
                                <a href="#">Abbigliamento</a>
                            </li>
                            <li>
                                <a href="#">Sport</a>
                            </li>
                            <li>
                                <a href="#">Per la casa</a>
                            </li>
                        </ul>
                    </li>
                    <?php
                        switch ($this->authInfo('livello')){
                            case 'user':?>
                            <li>
                                <a href="#">Gestione Profilo</a>
                            </li>
                            <li>
                                <a href="<?= $this->url(array(
                                            'controller' => 'user',
                                            'action'     => 'logout'), 
                                            'default',true); 
                                            ?>">Logout</a>
                            </li>
                            <?php break;
                        
                            case 'staff':?>
                            <li>
                                <a href="#">Strumenti Staff</a>
                            </li>
                            <li>
                                <a href="<?= $this->url(array(
                                            'controller' => 'staff',
                                            'action'     => 'logout'), 
                                            'default',true); 
                                            ?>">Logout</a>
                            </li>
                            <?php break;
                        
                            case 'admin':?>
                            <li>
                                <a href="<?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'amministrazione'), 
                                    'default',true); 
                                    ?>">Strumenti Amministratore</a>
                            </li>
                            <li>
                                <a href="<?= $this->url(array(
                                            'controller' => 'user',
                                            'action'     => 'logout'), 
                                            'default',true); 
                                            ?>">Logout</a>
                            </li>
                            <?php break;
                        
                            default:?>
                            <li>
                                <a href="<?= $this->url(array(
                                        'controller' => 'public',
                                        'action'     => 'logreg'), 
                                        'default',true); 
                                        ?>">Login/Registrati</a>
                            </li>
                        <?php
                            break;
                            }?>
                </ul>
                      <form class="navbar-form navbar-right" role="search">
                        <div class="form-group">
                          <input type="text" class="form-control" placeholder="Cerca coupon">
                        </div>
                        <button type="submit" class="btn btn-default">Cerca</button>
                      </form>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
