<?php echo $this->doctype() ?>	<!-- Inietto il doctype definito in Bootstrap-->
<html>
<head>
    
    <?= $this->headMeta(); ?>	<!-- Inietto le proprietà della head -->
    <?= $this->headLink(); ?>
    <?= $this->headTitle(); ?>
    <?= $this->headScript(); ?>


    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Sito specializzato nella distribuzione gratuita di coupon">
    <meta name="keywords" content="coupon, coupon is life , coupon per smartphone , coupon per la casa , coupon per la scuola , aziende jesi , coupon jesi ">
    <meta name="author" content="Gruppo 04">

</head>

<body>

    <?= $this->render('_navbar.phtml') ?>
    <?php echo $this->layout()->content; ?>
    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12"  style="text-align: center; background-color:#222222;">

            <p style="color: #9D9D9D"><strong>Gruppo 04 - 2016, All Rights Reserved</strong>
            <br>
            <span> Aturalyage Samith - Bianchini Giovanni - Cardinali Michele - Tesei Riccardo </span>

        </div>
    </footer>

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>
    
</body>
</html>

