<div class="container" style="text-align: center">
    <h3>Modifica dati personali</h3>
    <?= $this->datiForm; ?>
    <a class="btn btn-primary" href=" <?= $this->url(array(
                                    'controller' => 'user',
                                    'action'     => 'profilo',
                                    ), 
                                    'default',true); 
                                    ?>">Annulla</a>
    <br>
</div>

