<div class="container">
    <br>
    <h3><b>Modifica avvenuta con successo!</b></h3>
    <h4>Devi eseguire di nuovo l'accesso affinch&eacute; le modifiche abbiano effetto.</h4>
    <br>
    <a class="btn btn-primary" href=" <?= $this->url(array(
                                        'controller' => 'public',
                                        'action'     => 'login',
                                        ), 
                                        'default',true); 
                                        ?>">Vai alla pagina di login</a>
    <a class="btn btn-primary" href=" <?= $this->url(array(
                                        'controller' => 'public',
                                        'action'     => 'index',
                                        ), 
                                        'default',true); 
                                        ?>">Vai alla homepage</a>
</div>