<div class="container">
    <br><br>
    <div class="row">
        <div class="col-md-6">
            <ul style="list-style-type:none">
                <h2>Modifica informazioni profilo</h2>
                <li><a href="<?= $this->url(array(
                                        'controller' => 'user',
                                        'action'     => 'formdati',
                                        ), 
                                        'default',true); 
                            ?>"><h4>Modifica dati personali</h4></a></li>
                <li><a href="<?= $this->url(array(
                                        'controller' => 'user',
                                        'action'     => 'formpassword',
                                        ), 
                                        'default',true); 
                            ?>"><h4>Modifica password</h4></a></li>
            </ul>
            <br>
        </div>
        <div class="col-md-6">
            <ul style="list-style-type:none">
                <h2>Acquisisci coupon</h2>
                <li><a href="<?= $this->url(array(
                                        'controller' => 'public',
                                        'action'     => 'aziende',
                                        ), 
                                        'default',true); 
                            ?>"><h4>Vai alla pagina delle aziende</h4></a></li>
                <li><a href="<?= $this->url(array(
                                        'controller' => 'public',
                                        'action'     => 'categorie',
                                        ), 
                                        'default',true); 
                            ?>"><h4>Vai alla pagina delle categorie</h4></a></li>
            </ul>
        </div>
    </div>
</div>
