<div class="container">
    <br><br>
    <div class="row">
        <div class="col-md-12">
            <h2>Ciao <?= $this->dati->nome ?>!</h2>
            <br>
            <table class="table table-condensed">
                <tr><th>Nome</th><th>Cognome</th><th>Data di nascita</th><th>Genere</th><th>Provincia</th><th>Comune</th>
                    <th>e-mail</th><th>Telefono</th><th>Username</th></tr>
                <?php
                $dati = $this->dati;
                if($dati->telefono==null){
                            $telefono = 'NON DISPONIBILE';
                }
                echo '<tr><td>' . $dati->nome . '</td>'
                        . '<td>' . $dati->cognome . '</td>'
                        . '<td>' . $dati->data_di_nascita . '</td>'
                        . '<td>' . $dati->genere . '</td>'
                        . '<td>' . $dati->provincia . '</td>'
                        . '<td>' . $dati->citta . '</td>'
                        . '<td>' . $dati->email . '</td>'
                        . '<td>' . $telefono . '</td>'
                        . '<td>' . $dati->username . '</td>';
                ?>
            </table>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md-6">
            <ul style="list-style-type:none;">
                <h2>Modifica informazioni profilo</h2></th></tr>
                <li><td><a href="<?= $this->url(array(
                                        'controller' => 'user',
                                        'action'     => 'formdati',
                                        ), 
                                        'default',true); 
                                ?>"><h4>Modifica dati personali</h4></a></li>
                <li><a href="<?= $this->url(array(
                                        'controller' => 'user',
                                        'action'     => 'formpassword',
                                        ), 
                                        'default',true); 
                                ?>"><h4>Modifica password</h4></a></li>
            </ul>
            <br>
        </div>
        <div class="col-md-6">
            <ul style="list-style-type:none;">
                <h2>Acquisisci coupon</h2>
                <li><a href="<?= $this->url(array(
                                        'controller' => 'public',
                                        'action'     => 'aziende',
                                        ), 
                                        'default',true); 
                            ?>"><h4>Vai alla pagina delle aziende</h4></a></li>
                <li><a href="<?= $this->url(array(
                                        'controller' => 'public',
                                        'action'     => 'categorie',
                                        ), 
                                        'default',true); 
                            ?>"><h4>Vai alla pagina delle categorie</h4></a></li>
            </ul>
        </div>
    </div>
</div>
