<div>
    <br><br>
    <ul>
        <fieldset>
            <legend>Gestione aziende</legend>
            <li>Inserisci azienda</li>
            <li>Modifica/cancella azienda</li>
        </fieldset>
        <br><br>
        <fieldset>
            <legend>Gestione utenti</legend>
            <li><a href="<?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'users',
                                    ), 
                                    'default',true); 
                        ?>">Modifica/cancella utente</a></li>
        </fieldset>
        <br><br>
        <fieldset>
            <legend>Gestione staff</legend>
            <li><a href="<?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'formstaff',
                                    ), 
                                    'default',true); 
                        ?>">Inserisci membro staff</a></li>
            <li><a href="<?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'staff',
                                    ), 
                                    'default',true); 
                        ?>">Modifica/cancella membro staff</a></li>
        </fieldset>
        <br><br>
        <fieldset>
            <legend>Gestione categorie di prodotti</legend>
            <li>Inserisci nuova categoria</li>
            <li>Modifica/cancella categoria</li>  
        </fieldset>
        <br><br>
        <fieldset>
            <legend>Gestione promozioni</legend>
            <li>Visualizza statistiche relative ai coupon</li>
        </fieldset>
        <br><br>
        <fieldset>
            <legend>Gestione FAQ</legend>
            <li><a href="<?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'formfaq',
                                    ), 
                                    'default',true); 
                        ?>">Aggiungi domanda frequente</a></li>
            <li>Modifica/cancella domanda frequente</li>
        </fieldset>
    </ul>
</div>
