<div class="container">
    <br><br>
    <form action="<?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'formaziendamod',
                                    ), 
                                    'default',true); 
                        ?>" method="post">
        <table border>
            <tr><th>Seleziona</th><th>ID</th><th>Nome</th><th>Descrizione</th><th>Ragione sociale</th><th>Localizzazione</th>
                <th>Tipologia</th><th>Immagine</th>
            <?php
                foreach ($this->aziende as $azienda){
                    if($azienda->immagine==null){
                        $immagine = 'NON DISPONIBILE';
                    }
                    else{
                        $immagine = $azienda->immagine;
                    }
                echo '<tr><td><input type="radio" name="chosen" value="' . $azienda->id . '"</td>'
                        . '<td>' . $azienda->id . '</td>'
                        . '<td>' . $azienda->nome . '</td>'
                        . '<td>' . $azienda->descrizione . '</td>'
                        . '<td>' . $azienda->ragione_sociale . '</td>'
                        . '<td>' . $azienda->localizzazione . '</td>'
                        . '<td>' . $azienda->tipologia . '</td>'
                        . '<td>' . $immagine . '</td>';
            }?>
        </table>
        <br>
        <input type="submit" value="MODIFICA">
    </form>
</div>
