<div class="container">
    <br><br>
    <a class="btn btn-primary" href="<?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'amministrazione',
                                    ), 
                                    'default',true); 
                                    ?>">< Amministrazione</a><br><br>
    <form action="<?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'formaziendamod',
                                    ), 
                                    'default',true); 
                        ?>" method="get">
        <table class="table table-condensed">
            <tr><th style="text-align:center;">Seleziona</th><th style="text-align:center;">ID</th><th>Nome</th>
                <th>Descrizione</th><th>Ragione sociale</th><th>Localizzazione</th><th>Tipologia</th><th>Immagine</th>
            <?php
                foreach ($this->aziende as $azienda){
                    if($azienda->immagine==null){
                        $immagine = 'NON DISPONIBILE';
                    }
                    else{
                        $immagine = $azienda->immagine;
                    }
                echo '<tr><td style="text-align:center;"><input type="radio" name="chosen" value="' . $azienda->id . '"></td>'
                        . '<td style="text-align:center;">' . $azienda->id . '</td>'
                        . '<td>' . $azienda->nome . '</td>'
                        . '<td>' . $azienda->descrizione . '</td>'
                        . '<td>' . $azienda->ragione_sociale . '</td>'
                        . '<td>' . $azienda->localizzazione . '</td>'
                        . '<td>' . $azienda->tipologia . '</td>'
                        . '<td>' . $immagine . '</td>';
            }?>
        </table>
        <input class="btn btn-primary" type="submit" name="button"  value="Modifica/Cancella">
    </form>
</div>
