<div class="static">
    <br>
    <h5>Cancellazione azienda avvenuta con successo!</h5>
    <br>
    <ul>
        <li><a href=" <?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'aziende',
                                    ), 
                                    'default',true); 
                                    ?>">Modifica/cancella altre aziende</a>
        </li>
        <li><a href=" <?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'index',
                                    ), 
                                    'default',true); 
                                    ?>">Torna alla pagina di amministrazione</a>
        </li>
    </ul>
</div>


