<div class="container">
    <br>
    <h5>Cancellazione utente avvenuta con successo!</h5>
    <br>
    <ul>
        <li><a href=" <?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'users',
                                    ), 
                                    'default',true); 
                                    ?>">Modifica/cancella altri utenti</a>
        </li>
        <li><a href=" <?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'index',
                                    ), 
                                    'default',true); 
                                    ?>">Torna alla pagina di amministrazione</a>
        </li>
    </ul>
</div>


