<div class="container">
    <br>
    <h3><b>Cancellazione azienda avvenuta con successo!</b></h3>
    <br>
    <a href=" <?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'aziende',
                                    ), 
                                    'default',true); 
                                    ?>">Modifica/cancella altre aziende</a>
    <a href=" <?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'index',
                                    ), 
                                    'default',true); 
                                    ?>">Torna alla pagina di amministrazione</a>
</div>


