<div class="container">
    <br>
    <h3><b>Cancellazione categoria avvenuta con successo!</b></h3>
    <br>
    <a class="btn btn-primary" href=" <?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'categorie',
                                    ), 
                                    'default',true); 
                                    ?>">Modifica/cancella altre categorie</a>
    <a class="btn btn-primary" href=" <?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'index',
                                    ), 
                                    'default',true);
                                    ?>">Torna alla pagina di amministrazione</a>
</div>


