<div class="container">
    <br><br>
    <a class="btn btn-primary" href="<?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'amministrazione',
                                    ), 
                                    'default',true); 
                                    ?>">< Amministrazione</a><br><br>
    <form action="<?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'formcategoriamod',
                                    ), 
                                    'default',true); 
                        ?>" method="get">
        <table class="table table-condensed">
            <tr><th style="text-align:center;">Seleziona</th><th style="text-align:center;">ID</th><th>Nome</th>
                <th>Descrizione</th><th>Immagine</th>
            <?php
                foreach ($this->categorie as $categoria){
                    if($categoria->immagine==null){
                        $immagine = 'NON DISPONIBILE';
                    }
                    else{
                        $immagine = $categoria->immagine;
                    }
                echo '<tr><td style="text-align:center;"><input type="radio" name="chosen" value="' . $categoria->id . '"></td>'
                        . '<td style="text-align:center;">' . $categoria->id . '</td>'
                        . '<td>' . $categoria->nome . '</td>'
                        . '<td>' . $categoria->descrizione . '</td>'
                        . '<td>' . $immagine . '</td>';
            }?>
        </table>
        <br>
        <input class="btn btn-primary" type="submit" name="button"  value="Modifica/Cancella">
    </form>
</div>

