<div class="container">
    <br><br>
    <a class="btn btn-primary" href="<?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'amministrazione',
                                    ), 
                                    'default',true); 
                                    ?>">< Amministrazione</a><br><br>
    <form action="<?= $this->url(array(
                                'controller' => 'admin',
                                'action'     => 'formfaqmod',
                                ), 
                                'default',true); 
                    ?>" method="get">
        <table class="table table-condensed">
            <tr><th style="text-align:center;">Seleziona</th><th>ID</th><th>Domanda</th><th>Risposta</th>
            <?php
                foreach ($this->faq as $domanda){
                echo '<tr><td style="text-align:center;"><input type="radio" name="chosen" value="' . $domanda->id . '"></td>'
                        . '<td>' . $domanda->id . '</td>'
                        . '<td>' . $domanda->domanda . '</td>'
                        . '<td>' . $domanda->risposta . '</td>';
            }?>
        </table>
        <br>
        <input class="btn btn-primary" type="submit" name="button"  value="Modifica/Cancella">
    </form>
</div>