<div class="container">
    <br><br>
    <form action="<?= $this->url(array(
                                'controller' => 'admin',
                                'action'     => 'formfaqmod',
                                ), 
                                'default',true); 
                    ?>" method="get">
        <table border>
            <tr><th>Seleziona</th><th>ID</th><th>Domanda</th><th>Risposta</th>
            <?php
                foreach ($this->faq as $domanda){
                echo '<tr><td><input type="radio" name="chosen" value="' . $domanda->id . '"></td>'
                        . '<td>' . $domanda->id . '</td>'
                        . '<td>' . $domanda->domanda . '</td>'
                        . '<td>' . $domanda->risposta . '</td>';
            }?>
        </table>
        <br>
        <input type="submit" name="button"  value="Modifica">
    </form>
</div>