<div class="container">
    <br><br>
    <a class="btn btn-primary" href="<?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'amministrazione',
                                    ), 
                                    'default',true); 
                                    ?>">< Amministrazione</a><br>
    <h3><b>Aggiungi categoria</b></h3>
    <?= $this->categoriaForm; ?>
    <br>
</div>

