<div class="container">
    <br>
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3><b>Modifica domanda frequente</b></h3>
            </div>
            <div class="panel-body">
                <div role="form">
                    <?= $this->faqModForm; ?>
                    <a class="btn btn-primary" style="position: relative; left: 277px; bottom: 108px"
                       href="<?= $this->url(array(
                                                    'controller' => 'admin',
                                                    'action'     => 'faq',
                                                    ), 
                                                    'default',true); 
                                                    ?>">Annulla</a>
                </div>
            </div>
        </div>
    </div>
</div>

