<div class="container">
    <br><br>
    <a class="btn btn-primary" href="<?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'users',
                                    ), 
                                    'default',true); 
                                    ?>">< Utenti</a><br>
    <h3><b>Modifica utente</b></h3>
    <?= $this->userModForm; ?>
    <br>
</div>

