<div class="container">
    <br>
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3><b>Aggiungi membro staff</b></h3>
            </div>
            <div class="panel-body">
                <div role="form">   
                    <?= $this->staffForm; ?>
                    <a class="btn btn-primary" style="position: relative; left: 180px; bottom: 54px"
                       href="<?= $this->url(array(
                                                    'controller' => 'admin',
                                                    'action'     => 'amministrazione',
                                                    ), 
                                                    'default',true); 
                                                    ?>">Annulla</a><br>
                </div>
            </div>
        </div>
    </div>
</div>

