<?php $this->headScript()
	->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
	->appendFile($this->baseUrl('js/functions.js'))
	->captureStart() ?>

$(function()
{
	var actionUrl='<?= $this->url(array('controller' => 'admin', 'action' => 'validateaziendamod',), 'default'); ?>';
	var formName='<?= $this->aziendaModForm->getName() ?>';
	$(":input").on('blur', function(event) {
        var formElementId = $(this).attr('id');
        doValidation(formElementId, actionUrl, formName);
    });
});

<?php $this->headScript()->captureEnd() ?>

<div class="container">
    <br>
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3><b>Modifica azienda</b></h3>
            </div>
            <div class="panel-body">
                <div role="form">
                    <?= $this->aziendaModForm; ?>
                    <a class="btn btn-info" style="position: relative; left: 300px; bottom: 88px"
                       href="<?= $this->url(array(
                                        'controller' => 'admin',
                                        'action'     => 'aziende',
                                        ), 
                                        'default',true); 
                                        ?>">Annulla</a>
                </div>
            </div>
        </div>
    </div>
</div>

