<div class="container">
    <br><br>
    <a class="btn btn-primary" href="<?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'staff',
                                    ), 
                                    'default',true); 
                                    ?>">< Staff</a><br>
    <h3><b>Modifica membro staff</b></h3>
    <?= $this->staffModForm; ?>
    <br>
</div>

