<div class="container">
    <br>
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3><b>Modifica utente</b></h3>
            </div>
            <div class="panel-body">
                <div role="form">
                    <?= $this->userModForm; ?>
                    <a class="btn btn-primary" style="position: relative; left: 290px; bottom: 88px"
                       href="<?= $this->url(array(
                                                    'controller' => 'admin',
                                                    'action'     => 'userstomodify',
                                                    ), 
                                                    'default',true); 
                                                    ?>">Annulla</a><br>
                </div>
            </div>
        </div>
    </div>
</div>

