<div class="container">
    <br>
    <h5>Modifica avvenuta con successo!</h5>
    <br>
    <table border>
        <tr><th>Seleziona</th><th>ID</th><th>Domanda</th><th>Risposta</th>
        <?php
            $modificata = $this->modificata;
            echo '<tr><td><input type="radio" name="chosen" value="' . $modificata->id . '"></td>'
                    . '<td>' . $modificata->id . '</td>'
                    . '<td>' . $modificata->domanda . '</td>'
                    . '<td>' . $modificata->risposta . '</td>';
        ?>
    </table>
    <br><br>
    <ul>
        <li><a href=" <?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'faq',
                                    ), 
                                    'default',true); 
                                    ?>">Modifica/cancella altre FAQ</a>
        </li>
        <li><a href=" <?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'index',
                                    ), 
                                    'default',true); 
                                    ?>">Torna alla pagina di amministrazione</a>
        </li>
    </ul>
</div>


