<div class="container">
    <br>
    <h3><b>Modifica avvenuta con successo!</b></h3>
    <br>
    <table class="table table-condensed">
            <tr><th>ID</th><th>Nome</th><th>Cognome</th><th>Sesso</th><th>Data di nascita</th>
            <th>Provincia</th><th>Comune</th><th>email</th><th>Telefono</th>
            <th>Username</th><th>Password</th>
            <?php
                $modificato = $this->modificato;
                if($modificato->telefono==0){
                    $telefono = 'NON DISPONIBILE';
                }
                else{
                    $telefono = $modificato->telefono;
                }
                echo '<tr><td>' . $modificato->id . '</td>'
                        . '<td>' . $modificato->nome . '</td>'
                        . '<td>' . $modificato->cognome . '</td>'
                        . '<td>' . $modificato->genere . '</td>'
                        . '<td>' . $modificato->data_di_nascita . '</td>'
                        . '<td>' . $modificato->provincia . '</td>'
                        . '<td>' . $modificato->citta . '</td>'
                        . '<td>' . $modificato->email . '</td>'
                        . '<td>' . $telefono . '</td>'
                        . '<td>' . $modificato->username . '</td>'
                        . '<td>' . $modificato->password . '</td>';
            ?>
    </table>
    <br>
    <a class="btn btn-primary" href=" <?= $this->url(array(
                                'controller' => 'admin',
                                'action'     => 'users',
                                ), 
                                'default',true); 
                                ?>">Modifica/cancella altri utenti</a>
    <a class="btn btn-primary" href=" <?= $this->url(array(
                            'controller' => 'admin',
                            'action'     => 'index',
                            ), 
                            'default',true); 
                            ?>">Torna alla pagina di amministrazione</a>
</div>


