<div class="container">
    <br>
    <h3><b>Modifica avvenuta con successo!</b></h3>
    <br>
    <table class="table table-condensed">
            <tr><th>ID</th><th>Nome</th><th>Cognome</th><th>email</th><th>Username</th><th>Password</th>
            <?php
                $modificato = $this->modificato;
                echo '<tr><td>' . $modificato->id . '</td>'
                    . '<td>' . $modificato->nome . '</td>'
                    . '<td>' . $modificato->cognome . '</td>'
                    . '<td>' . $modificato->email . '</td>'
                    . '<td>' . $modificato->username . '</td>'
                    . '<td>' . $modificato->password . '</td>';
            ?>
    </table>
    <br>
    <a class="btn btn-primary" href=" <?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'staff',
                                    ), 
                                    'default',true); 
                                    ?>">Modifica/cancella altri membri staff</a>
    <a class="btn btn-primary" href=" <?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'index',
                                    ), 
                                    'default',true); 
                                    ?>">Torna alla pagina di amministrazione</a>
</div>


