<div class="container">
    <br>
    <h3><b>Modifica avvenuta con successo!</b></h3>
    <br>
    <table class="table table-condensed">
        <tr><th style="text-align:center;">ID</th><th>Domanda</th><th>Risposta</th>
        <?php
            $modificata = $this->modificata;
            echo '<tr><td style="text-align:center;">' . $modificata->id . '"></td>'
                    . '<td>' . $modificata->id . '</td>'
                    . '<td>' . $modificata->domanda . '</td>'
                    . '<td>' . $modificata->risposta . '</td>';
        ?>
    </table>
    <br>
    <a class="btn btn-primary" href=" <?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'faq',
                                    ), 
                                    'default',true); 
                                    ?>">Modifica/cancella altre FAQ</a>
    <a class="btn btn-primary" href=" <?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'index',
                                    ), 
                                    'default',true); 
                                    ?>">Torna alla pagina di amministrazione</a>
</div>


