<div class="container">
    <br>
    <h3><b>Registrazione membro staff avvenuta con successo!</b></h3>
    <br>
    <table class="table table-condensed">
            <tr><th style="text-align:center;">ID</th><th>Nome</th><th>Cognome</th><th>email</th><th>Username</th><th>Password</th>
            <?php
                $aggiunto = $this->aggiunto;
                echo '<tr><td style="text-align:center;">' . $aggiunto->id . '</td>'
                    . '<td>' . $aggiunto->nome . '</td>'
                    . '<td>' . $aggiunto->cognome . '</td>'
                    . '<td>' . $aggiunto->email . '</td>'
                    . '<td>' . $aggiunto->username . '</td>'
                    . '<td>' . $aggiunto->password . '</td>';
            ?>
    </table>
    <a class="btn btn-primary" href=" <?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'formstaff',
                                    ), 
                                    'default',true); 
                                    ?>">Aggiungi altri membri</a>
    <a class="btn btn-primary" href=" <?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'index',
                                    ), 
                                    'default',true); 
                                    ?>">Torna alla pagina di amministrazione</a>
</div>


