<div class="container">
    <br>
    <h3><b>Registrazione membro staff avvenuta con successo!</b></h3>
    <br>
    <a class="btn btn-primary" href=" <?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'formstaff',
                                    ), 
                                    'default',true); 
                                    ?>">Aggiungi altri membri</a>
    <a class="btn btn-primary" href=" <?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'index',
                                    ), 
                                    'default',true); 
                                    ?>">Torna alla pagina di amministrazione</a>
</div>


