<div class="container">
    <br>
    <h3><b>Registrazione azienda avvenuta con successo!</b></h3>
    <br>
    <table class="table table-condensed">
            <tr><th style="text-align:center;">ID</th><th>Nome</th><th>Descrizione</th><th>Ragione sociale</th>
                <th>Localizzazione</th><th>Tipologia</th><th>Immagine</th>
            <?php
                $aggiunta = $this->aggiunta;
                if($aggiunta->immagine==null){
                        $immagine = 'NON DISPONIBILE';
                    }
                    else{
                        $immagine = $aggiunta->immagine;
                    }
                echo '<tr><td style="text-align:center;">' . $aggiunta->id . '</td>'
                        . '<td>' . $aggiunta->nome . '</td>'
                        . '<td>' . $aggiunta->descrizione . '</td>'
                        . '<td>' . $aggiunta->ragione_sociale . '</td>'
                        . '<td>' . $aggiunta->localizzazione . '</td>'
                        . '<td>' . $aggiunta->tipologia . '</td>'
                        . '<td>' . $immagine . '</td>';
            ?>
    </table>
    <br>
    <a class="btn btn-primary" href=" <?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'formazienda',
                                    ), 
                                    'default',true); 
                                    ?>">Aggiungi altre aziende</a>
    <a class="btn btn-primary" href=" <?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'index',
                                    ), 
                                    'default',true); 
                                    ?>">Torna alla pagina di amministrazione</a>
</div>


