<div class="container">
    <br><br>
    <form action="<?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'formstaffmod',
                                    ), 
                                    'default',true); 
                        ?>" method="get">
        <table border>
            <tr><th>ID</th><th>Nome</th><th>Cognome</th><th>email</th><th>Username</th><th>Password</th>
            <?php
                foreach ($this->staff as $membrostaff){
                echo '<tr><td><input type="radio" name="chosen" value="' . $membrostaff->id . '"></td>'
                        . '<td>' . $membrostaff->nome . '</td>'
                        . '<td>' . $membrostaff->cognome . '</td>'
                        . '<td>' . $membrostaff->email . '</td>'
                        . '<td>' . $membrostaff->username . '</td>'
                        . '<td>' . $membrostaff->password . '</td>';
            }?>
        </table>
        <br>
        <input type="submit" name="button"  value="Modifica">
    </form>
</div>