<div class="container">
    <br><br>
    <a class="btn btn-primary" href="<?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'amministrazione',
                                    ), 
                                    'default',true); 
                                    ?>">< Amministrazione</a>
    <h4 style="text-align:right;"><b>Totale membri staff:&emsp;<?= $this->numero ?></b></h4><br>
    <form action="<?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'formstaffmod',
                                    ), 
                                    'default',true); 
                        ?>" method="get">
        <table class="table table-condensed">
            <tr><th style="text-align:center;">Seleziona</th><th style="text-align:center;">ID</th><th>Nome</th>
                <th>Cognome</th><th>email</th><th>Username</th><th>Password</th>
            <?php
                foreach ($this->staff as $membrostaff){
                echo '<tr><td style="text-align:center;"><input type="radio" name="chosen" value="' . $membrostaff->id . '"></td>'
                        . '<td style="text-align:center;">' . $membrostaff->id . '</td>'
                        . '<td>' . $membrostaff->nome . '</td>'
                        . '<td>' . $membrostaff->cognome . '</td>'
                        . '<td>' . $membrostaff->email . '</td>'
                        . '<td>' . $membrostaff->username . '</td>'
                        . '<td>' . $membrostaff->password . '</td>';
            }?>
        </table>
        <br>
        <input class="btn btn-primary" type="submit" name="button"  value="Modifica/Cancella">
    </form>
</div>