<div class="container">
    <br><br>
    <a class="btn btn-primary" href="<?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'amministrazione',
                                    ), 
                                    'default',true); 
                                    ?>">< Amministrazione</a><br><br>
    <form action="<?= $this->url(array(
                                    'controller' => 'admin',
                                    'action'     => 'cancellauser',
                                    ), 
                                    'default',true); 
                        ?>" method="get">
        <table class="table table-condensed">
            <tr><th style="text-align:center;">Seleziona</th><th style="text-align:center;">ID</th><th>Nome</th>
                <th>Cognome</th><th>Sesso</th><th>Data di nascita</th><th>Provincia</th><th>Comune</th><th>email</th>
                <th>Telefono</th><th>Username</th><th>Password</th>
            <?php
                foreach ($this->users as $user){
                    if($user->telefono==0){
                        $telefono = 'NON DISPONIBILE';
                    }
                    else{
                        $telefono = $user->telefono;
                    }
                echo '<tr><td style="text-align:center;"><input type="radio" name="chosen" value="' . $user->id . '"></td>'
                        . '<td style="text-align:center;">' . $user->id . '</td>'
                        . '<td>' . $user->nome . '</td>'
                        . '<td>' . $user->cognome . '</td>'
                        . '<td>' . $user->genere . '</td>'
                        . '<td>' . $user->data_di_nascita . '</td>'
                        . '<td>' . $user->provincia . '</td>'
                        . '<td>' . $user->citta . '</td>'
                        . '<td>' . $user->email . '</td>'
                        . '<td>' . $telefono . '</td>'
                        . '<td>' . $user->username . '</td>'
                        . '<td>' . $user->password . '</td>';
            }?>
        </table>
        <br>
        <input class="btn btn-primary" type="submit" name="button"  value="Cancella">
    </form>
</div>
