<div class="container">
    <br><br>
    <table border>
        <tr><th>ID</th><th>Nome</th><th>Cognome</th><th>Sesso</th><th>Data di nascita</th>
            <th>Provincia</th><th>Citt&agrave;</th><th>email</th><th>Telefono</th>
            <th>Username</th><th>Password</th>
        <?php
            foreach ($this->users as $user){
                if($user->telefono==0){
                    $telefono = 'NON DISPONIBILE';
                }
                else{
                    $telefono = $user->telefono;
                }
            echo '<tr><td>' . $user->id . '</td>'
                    . '<td>' . $user->nome . '</td>'
                    . '<td>' . $user->cognome . '</td>'
                    . '<td>' . $user->genere . '</td>'
                    . '<td>' . $user->data_di_nascita . '</td>'
                    . '<td>' . $user->provincia . '</td>'
                    . '<td>' . $user->citta . '</td>'
                    . '<td>' . $user->email . '</td>'
                    . '<td>' . $telefono . '</td>'
                    . '<td>' . $user->username . '</td>'
                    . '<td>' . $user->password . '</td>';
        }?>
    </table>
</div>
